### ISSUE TITLE
Error compile scala.matchError

### ISSUE THREAD

**Issue by BermudezK** [omp4j/omp4j#17]
Hi! I need help with this. I wanna compile this code but omp4j send me this error...
Can you show me what is wrong with my code?

The configuration context created
Running first preprocessor level
Parsing file '/home/karinabermudez/Documentos/ASOA/ASOA/src/modeloHidrologico/DistribucionEmpirica.java'
Trying fast SLL method...
Failed, trying standard LL method instead...
Successfully
Validating file /home/karinabermudez/Documentos/ASOA/ASOA/src/modeloHidrologico/DistribucionEmpirica.java
Compiling for validation
[parsing started SimpleFileObject[/tmp/.omp4j-103292991845098850414140821653125/validation-55260039198513093574140888704078/modeloHidrologico/DistribucionEmpirica.java]]
[parsing completed 105ms]
[loading /modules/java.xml.ws.annotation/module-info.class]
[loading /modules/java.sql.rowset/module-info.class]
[loading /modules/java.rmi/module-info.class]
[loading /modules/jdk.aot/module-info.class]
[loading /modules/jdk.jdwp.agent/module-info.class]
[loading /modules/jdk.xml.dom/module-info.class]
[loading /modules/jdk.jsobject/module-info.class]
[loading /modules/java.management/module-info.class]
[loading /modules/jdk.jartool/module-info.class]
[loading /modules/java.instrument/module-info.class]
[loading /modules/jdk.unsupported/module-info.class]
[loading /modules/jdk.jshell/module-info.class]
[loading /modules/jdk.jlink/module-info.class]
[loading /modules/jdk.internal.jvmstat/module-info.class]
[loading /modules/java.security.sasl/module-info.class]
[loading /modules/java.xml.crypto/module-info.class]
[loading /modules/java.prefs/module-info.class]
[loading /modules/java.se/module-info.class]
[loading /modules/jdk.jstatd/module-info.class]
[loading /modules/java.scripting/module-info.class]
[loading /modules/jdk.security.auth/module-info.class]
[loading /modules/jdk.compiler/module-info.class]
[loading /modules/java.management.rmi/module-info.class]
[loading /modules/java.desktop/module-info.class]
[loading /modules/jdk.naming.dns/module-info.class]
[loading /modules/jdk.jdeps/module-info.class]
[loading /modules/jdk.internal.opt/module-info.class]
[loading /modules/java.smartcardio/module-info.class]
[loading /modules/jdk.management.agent/module-info.class]
[loading /modules/jdk.naming.rmi/module-info.class]
[loading /modules/jdk.management/module-info.class]
[loading /modules/jdk.xml.bind/module-info.class]
[loading /modules/jdk.security.jgss/module-info.class]
[loading /modules/jdk.jdi/module-info.class]
[loading /modules/jdk.internal.vm.ci/module-info.class]
[loading /modules/java.naming/module-info.class]
[loading /modules/jdk.internal.vm.compiler.management/module-info.class]
[loading /modules/jdk.internal.le/module-info.class]
[loading /modules/jdk.rmic/module-info.class]
[loading /modules/jdk.internal.ed/module-info.class]
[loading /modules/jdk.net/module-info.class]
[loading /modules/jdk.sctp/module-info.class]
[loading /modules/java.datatransfer/module-info.class]
[loading /modules/jdk.jconsole/module-info.class]
[loading /modules/jdk.dynalink/module-info.class]
[loading /modules/jdk.charsets/module-info.class]
[loading /modules/jdk.zipfs/module-info.class]
[loading /modules/java.sql/module-info.class]
[loading /modules/java.security.jgss/module-info.class]
[loading /modules/jdk.crypto.cryptoki/module-info.class]
[loading /modules/jdk.localedata/module-info.class]
[loading /modules/jdk.scripting.nashorn/module-info.class]
[loading /modules/jdk.accessibility/module-info.class]
[loading /modules/jdk.httpserver/module-info.class]
[loading /modules/jdk.xml.ws/module-info.class]
[loading /modules/jdk.attach/module-info.class]
[loading /modules/java.xml/module-info.class]
[loading /modules/jdk.incubator.httpclient/module-info.class]
[loading /modules/jdk.jcmd/module-info.class]
[loading /modules/java.se.ee/module-info.class]
[loading /modules/java.activation/module-info.class]
[loading /modules/jdk.editpad/module-info.class]
[loading /modules/jdk.pack/module-info.class]
[loading /modules/java.base/module-info.class]
[loading /modules/java.xml.ws/module-info.class]
[loading /modules/jdk.crypto.ec/module-info.class]
[loading /modules/java.corba/module-info.class]
[loading /modules/java.logging/module-info.class]
[loading /modules/java.transaction/module-info.class]
[loading /modules/java.xml.bind/module-info.class]
[loading /modules/jdk.hotspot.agent/module-info.class]
[loading /modules/jdk.javadoc/module-info.class]
[loading /modules/jdk.scripting.nashorn.shell/module-info.class]
[loading /modules/jdk.internal.vm.compiler/module-info.class]
[loading /modules/java.compiler/module-info.class]
[search path for source files: /tmp/.omp4j-103292991845098850414140821653125/compilation-133572008993364021424140889405711]
[search path for class files: /usr/lib/jvm/java-11-openjdk-amd64/lib/modules,/tmp/.omp4j-103292991845098850414140821653125/compilation-133572008993364021424140889405711]
[search path for source files: /tmp/.omp4j-103292991845098850414140821653125/compilation-133572008993364021424140889405711]
[search path for class files: /usr/lib/jvm/java-11-openjdk-amd64/lib/modules,/tmp/.omp4j-103292991845098850414140821653125/compilation-133572008993364021424140889405711]
[loading /modules/java.base/java/lang/Object.class]
[loading /modules/java.base/java/util/ArrayList.class]
[loading /modules/java.base/java/lang/Integer.class]
[loading /modules/java.base/java/lang/Double.class]
[loading /modules/java.base/java/lang/Deprecated.class]
[loading /modules/java.base/java/lang/annotation/Retention.class]
[loading /modules/java.base/java/lang/annotation/RetentionPolicy.class]
[loading /modules/java.base/java/lang/annotation/Target.class]
[loading /modules/java.base/java/lang/annotation/ElementType.class]
[checking modeloHidrologico.DistribucionEmpirica]
[loading /modules/java.base/java/io/Serializable.class]
[loading /modules/java.base/java/lang/AutoCloseable.class]
[loading /modules/java.base/java/util/Collection.class]
[loading /modules/java.base/java/util/Arrays.class]
[loading /modules/java.base/java/util/List.class]
[loading /modules/java.base/java/lang/Number.class]
[loading /modules/java.base/java/lang/Comparable.class]
[loading /modules/java.base/java/lang/Byte.class]
[loading /modules/java.base/java/lang/Character.class]
[loading /modules/java.base/java/lang/Short.class]
[loading /modules/java.base/java/lang/Long.class]
[loading /modules/java.base/java/lang/Float.class]
[loading /modules/java.base/java/lang/String.class]
[wrote DirectoryFileObject[/tmp/.omp4j-103292991845098850414140821653125/compilation-133572008993364021424140889405711:modeloHidrologico/DistribucionEmpirica.class]]
[total 2302ms]
Packing for validation
JAR saved
Translating a file...
Building directive hierarchy model
scala.MatchError: List((/tmp/.omp4j-103292991845098850414140821653125,/tmp/.omp4j-103292991845098850414140821653125/preprocessed-116710214497226296994140887898716)) (of class scala.collection.immutable.$colon$colon)
	at org.omp4j.Main$delayedInit$body.apply(Main.scala:31)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
	at scala.App$class.main(App.scala:71)
	at org.omp4j.Main$.main(Main.scala:17)
	at org.omp4j.Main.main(Main.scala)
Deleting work directories...
Exception in thread "main" java.lang.NullPointerException
	at org.omp4j.Main$delayedInit$body.apply(Main.scala:61)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
	at scala.App$class.main(App.scala:71)
	at org.omp4j.Main$.main(Main.scala:17)
	at org.omp4j.Main.main(Main.scala)

**Comment by petrbel** [comment]
Hi,
would you mind sending the `.java` file you're trying to preprocess? Please make sure to use triple "```" in order to get the code formatted.
I'm not sure I'll be able to helo you due to a limited time I have for this project, though.

**Comment by BermudezK** [comment]
Hi!, I solved the problem, thanks for reply my question. I forgot to put an OMP4J directive in the file.

Thanks

**Comment by petrbel** [comment]
Oh! Good to hear that, however, I think omp4j shouldn't fail in this case. See #19.

Would you like to contribute to the project and fix this? It should be like 2-3 lines...
