### ISSUE TITLE
Time spent using Omp4j is bigger than not using Omp4j??? Am I doing somthing wrong???

### ISSUE THREAD

**Issue by tcelio2** [omp4j/omp4j#2]
Hi,

I am attempt to improve the time of some Omp4j examples from your home page. I choose this example:

class Example2 {
    public static void main(String[] args) {

```
    long start = System.nanoTime();

    // omp parallel for
    for (int i = 0; i < 50; i += 2) {
        System.out.print(" " + i);
    }

    long end = System.nanoTime();
    long microseconds = (end - start) / 1000;
    System.out.print("Time spent: "+microseconds+"\n\n");
}
```

}

Obs.: The yellow highlight is the Omp4j annotation, and the green part is my "timer analitics".

So, the time spent when I use Omp4j is bigger than when I dont use it. I try other examples, but the problem is happen again.

Running case:
Using Omp4j: +- 8000 ms
Not using Omp4j: +- 800ms

Obs.: In all other examples, the time spent including Omp4j is bigger then without use it.

How I compile(in Linux):
I compile the .java using:
 java -jar omp4j-1.2.jar Example2.java
and then:
java Example2.

Am I doing something wrong?? Could you help me?????

Thanks a lot!!!!

**Comment by petrbel** [comment]
Hi,
firstly it's important to distinguish between a simple example and real-world application.

If you attempt to run only 50 iterations in parallel, the overhead of creating new threads is enormously disproportional (yes, internally there are new threads allocated and started). The other problem with the example is that it prints stuff to `stdout`. As you may know, there is an implicit serialization hence another overhead. This particular example can't be faster than its serial version, ever!

**Why I posted such example**, you may ask. Well it is supposed to demonstrate a basic principles of the preprocessor usage. By trying it you should understand how the directives work, how to compile the code etc.

**Where could you get some interesting benchmarks**, you may ask as well :) Well there's a repository [omp4j/benchmark](https://github.com/omp4j/benchmark/tree/master/resources) which contains few examples. In addition, you may find there JOMP implementation of these benchmarks. In that way you can easily compare the performance.

If you are further interested in additional benchmarks, their analysis and some statistical models of their behavior, please read my [bachelor thesis](https://is.cuni.cz/webapps/zzp/download/130155774/?lang=cs). As you will see, the speedup is actually almost linear in real-world examples. If you're interested in using omp4j I recommend you to read it anyway :))) - it clarifies the methodology of source code preprocessing etc.

If you need any further help or something isn't clear, please let me know via issue or e-mail.
