### ISSUE TITLE
 package org.omp4j.runtime does not exist incase another jar file is used in the project

### ISSUE THREAD

**Issue by TyrionLanister** [omp4j/omp4j#7]
Hi @petrbel 
Any idea why this doesnt compile if Example1.java needs "Any.jar" 

java  -jar omp4j-1.2.jar -cp Any.jar Example1.java

Errors:
 1. error: package org.omp4j.runtime does not exist
final org.omp4j.runtime.IOMPExecutor ompExecutor = new org.omp4j.runtime.DynamicExecutor(Runtime.getRuntime().availableProcessors());
2. org.omp4j.runtime.IOMPExecutor ompExecutor = new org.omp4j.runtime.DynamicExecutor(Runtime.getRuntime().availableProcessors());

**Comment by astyelp** [comment]
By setting the classpath this way you make java search for omp4j runtime classes exclusively in your jarfile Any.jar, where they are not.
If you add the omp4j-1.2.jar to the classpath like:
java -jar omp4j-1.2.jar -cp Any.jar:omp4j-1.2.jar Example1.java
it might work.

**Comment by TyrionLanister** [comment]
@astyelp 
: is probably for linux? For Windows this command works>
java -jar omp4j-1.2.jar -cp Any.jar;omp4j-1.2.jar Example1.java

omp4j  would have been extended to scala but still feasible to invoke java code from scala.
